### ISSUE TITLE
A really helpful repo

### ISSUE THREAD

**Issue by hamzabinrashid** [MrPr0fessor/TryHackMe-Roadmap-Beginners#1]
This repo really helped me in solving my tryhackme labs kudos to MrPr0fessor

**Comment by kh12kali** [comment]
A very informative and helpful repo 
My tryhackme username is : danyalshinwarizl
![IMG_8630](https://github.com/MrPr0fessor/TryHackMe-Roadmap-Beginners/assets/141318786/3286cc11-f5b4-4920-8da3-352dd18f7049)
